### ISSUE TITLE
Heyyyy I see you are using StackMob, and you added Folia support.

### ISSUE THREAD

**Issue by Yomamaeatstoes** [Yive/Pluto#1]
Is it okay if I upstream it, and do a PR to the main branch using your fork?

**Comment by Yive** [comment]
Sure, go right ahead. That fork was more of a test back when I had early access to Folia so I can't confirm if its actually safe or not especially with how much Folia has changed since March.

**Comment by Yomamaeatstoes** [comment]
Okay thank you very much! I appreciate it! I have just created a PR of it. 

Did you get Folia early on before it was announced?

**Comment by Yomamaeatstoes** [comment]
It got merged! Thank you very much!

**Comment by Yive** [comment]
> Did you get Folia early on before it was announced?

No, I only got access a week or so prior to being made open source.


> It got merged! Thank you very much!

Glad to hear, surprised it didn't have any bugs that needed fixing.
